spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  liquibase:
    # 开启 liquibase
    enabled: true
    # 配置 changlog 文件路径
    change-log: classpath:/db/changelog/changelog-master.xml
